# -*- coding: utf-8 -*-
"""mfun.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MpPsbh5_MRdef_dqZY--plbMxZBUDB4R
"""

def kMiddleMean(k,windElem):
    Length_windElem = len(windElem)
#     check odd or even
    if((Length_windElem%2) == 1):
#         for odd
        half_lengh = int((Length_windElem+1)/2)
        factor = 1/(2*k - 1)
        K_middle_vector=windElem.range((half_lengh-k+1),(half_lengh+k-1))
        sum_of_element=K_middle_vector.sum()
            
    else:
#         for even
        half_lengh = 0.5*(Lenght_windElem)
        factor = 1/(2*k)
        K_middle_vector=windElem.range((half_lengh-k+1),(half_lengh+k))
        sum_of_element=K_middle_vector.sum()
            
    mean=factor*sum_of_element
    return mean

def type2_MF(winElem):
    r=len(winElem)
    c=len(winElem[0])
    p=r*c
    H=(1+p)/2
    mu=(1,H)
    np.zeros(mu)
    for q in range(1,H):
#     (5)
        mu[1,q]=kMiddleMean(q,winElem)
#     (7)
    average_mu=((mu.sum())/H)*(np.ones(1,p))
    tmp= abs(winElem-average_mu)
    mu_Mat=np.matlib.repmat(mu,p,1)
    tmp_vector=np.matlib.repmat(winElem,H,1);
#     (6)
    sigma=kMiddleMean(H,tmp)
    if (sigma < 0.0001):
        sigma = 0.0001
#     (4)
    PI= math.exp(-0.5*((tmp_vector-mu_Mat)/sigma))
    np.power(PI,2)

    dx = (PI.sum())/H
    Tx= math.exp(-dx)
    Ax=PI.min()
    A= Ax.sum()/H
   
    return Tx, A